-- ============================================================
-- Vben Admin 配套后端 RBAC 表结构（对齐若依 RuoYi-Vue 经典模型）
-- PostgreSQL 版本。首次部署：先建库
--   CREATE DATABASE vben5;
-- 再执行本文件。所有语句幂等（IF NOT EXISTS），
-- 配合 spring.sql.init.mode: always 可每次启动重复执行。
-- 注意：update_time 自动更新由应用层 MyBatis-Plus MetaObjectHandler 完成，
-- 本脚本不包含 PL/pgSQL 函数/触发器（Spring SQL 初始化器不支持 $$ 美元引用）。
-- ============================================================

CREATE TABLE IF NOT EXISTS sys_user (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username    VARCHAR(64)  NOT NULL,
  password    VARCHAR(128) NOT NULL,
  nickname    VARCHAR(64)  NOT NULL DEFAULT '',
  home_path   VARCHAR(255) NULL,
  dept_id     BIGINT       NULL,
  status      SMALLINT     NOT NULL DEFAULT 0,
  create_time TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_user_username UNIQUE (username)
);
CREATE INDEX IF NOT EXISTS idx_user_dept ON sys_user (dept_id);
COMMENT ON TABLE sys_user IS '用户表';
COMMENT ON COLUMN sys_user.password IS 'BCrypt 哈希';
COMMENT ON COLUMN sys_user.nickname IS '显示名(对应前端 realName)';
COMMENT ON COLUMN sys_user.home_path IS '登录后首页(可选)';
COMMENT ON COLUMN sys_user.dept_id IS '所属部门id(sys_dept.id),NULL=未归属';
COMMENT ON COLUMN sys_user.status IS '0正常 1停用';

CREATE TABLE IF NOT EXISTS sys_dept (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id   BIGINT       NOT NULL DEFAULT 0,
  dept_name   VARCHAR(64)  NOT NULL,
  leader      VARCHAR(64)  NULL,
  status      SMALLINT     NOT NULL DEFAULT 0,
  order_num   INT          NOT NULL DEFAULT 0,
  remark      VARCHAR(255) NULL,
  create_time TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_dept_parent ON sys_dept (parent_id);
COMMENT ON TABLE sys_dept IS '部门表';
COMMENT ON COLUMN sys_dept.parent_id IS '父部门id,0=根部门';
COMMENT ON COLUMN sys_dept.leader IS '负责人姓名(仅存字段)';
COMMENT ON COLUMN sys_dept.status IS '0正常 1停用';

CREATE TABLE IF NOT EXISTS sys_role (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_key    VARCHAR(64) NOT NULL,
  role_name   VARCHAR(64) NOT NULL,
  sort_num    INT         NOT NULL DEFAULT 0,
  status      SMALLINT    NOT NULL DEFAULT 0,
  remark      VARCHAR(255) NULL,
  data_scope  CHAR(1)     NOT NULL DEFAULT '5',
  create_time TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_role_key UNIQUE (role_key)
);
COMMENT ON TABLE sys_role IS '角色表';
COMMENT ON COLUMN sys_role.role_key IS '角色标识(对应前端 roles 数组元素)';
COMMENT ON COLUMN sys_role.data_scope IS '数据范围:1全部 2自定义部门 3本部门 4本部门及以下 5仅本人';

-- 数据范围-自定义部门关联表（仅 data_scope=2 时读写）
CREATE TABLE IF NOT EXISTS sys_role_dept (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id BIGINT NOT NULL,
  dept_id BIGINT NOT NULL,
  CONSTRAINT uk_role_dept UNIQUE (role_id, dept_id)
);
COMMENT ON TABLE sys_role_dept IS '角色自定义数据部门关联表';
COMMENT ON COLUMN sys_role_dept.dept_id IS '部门id(含其子孙部门)';
COMMENT ON COLUMN sys_role.status IS '0正常 1停用';

CREATE TABLE IF NOT EXISTS sys_menu (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id    BIGINT       NOT NULL DEFAULT 0,
  menu_name    VARCHAR(64)  NOT NULL,
  menu_type    CHAR(1)      NOT NULL,
  title        VARCHAR(128) NOT NULL,
  icon         VARCHAR(128) NULL,
  order_num    INT          NOT NULL DEFAULT 0,
  path         VARCHAR(255) NULL,
  component    VARCHAR(255) NULL,
  redirect     VARCHAR(255) NULL,
  perm         VARCHAR(128) NULL,
  visible      SMALLINT     NOT NULL DEFAULT 0,
  keep_alive   SMALLINT     NOT NULL DEFAULT 0,
  affix_tab    SMALLINT     NOT NULL DEFAULT 0,
  authority    VARCHAR(255) NULL,
  extra_meta   VARCHAR(1024) NULL,
  status       SMALLINT     NOT NULL DEFAULT 0,
  create_time  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_menu_name UNIQUE (menu_name)
);
CREATE INDEX IF NOT EXISTS idx_menu_parent ON sys_menu (parent_id);
COMMENT ON TABLE sys_menu IS '菜单权限表';
COMMENT ON COLUMN sys_menu.menu_name IS '路由 name(全局唯一)';
COMMENT ON COLUMN sys_menu.menu_type IS 'M目录 C菜单 F按钮(不进路由树,仅权限码)';
COMMENT ON COLUMN sys_menu.title IS '显示名,支持 i18n key 如 page.dashboard.title';
COMMENT ON COLUMN sys_menu.component IS '前端页面组件路径,如 /dashboard/analytics/index';
COMMENT ON COLUMN sys_menu.perm IS '权限码,如 System:User:List';
COMMENT ON COLUMN sys_menu.visible IS '0显示 1隐藏(hideInMenu)';
COMMENT ON COLUMN sys_menu.affix_tab IS '固定标签页';
COMMENT ON COLUMN sys_menu.authority IS '访问角色,逗号分隔,映射 meta.authority';
COMMENT ON COLUMN sys_menu.extra_meta IS 'vben meta 扩展 JSON,转换时合并,如 {"badge":"new"}';
COMMENT ON COLUMN sys_menu.status IS '0正常 1停用';

CREATE TABLE IF NOT EXISTS sys_user_role (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  CONSTRAINT uk_user_role UNIQUE (user_id, role_id)
);
COMMENT ON TABLE sys_user_role IS '用户角色关联表';

CREATE TABLE IF NOT EXISTS sys_role_menu (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id BIGINT NOT NULL,
  menu_id BIGINT NOT NULL,
  CONSTRAINT uk_role_menu UNIQUE (role_id, menu_id)
);
COMMENT ON TABLE sys_role_menu IS '角色菜单关联表';

CREATE TABLE IF NOT EXISTS sys_oper_log (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  oper_user_id    BIGINT        NULL,
  oper_name       VARCHAR(64)   NULL,
  module          VARCHAR(64)   NOT NULL,
  description     VARCHAR(255)  NULL,
  method          VARCHAR(255)  NULL,
  request_method  VARCHAR(16)   NULL,
  request_url     VARCHAR(255)  NULL,
  params          VARCHAR(2000) NULL,
  status          SMALLINT      NOT NULL DEFAULT 0,
  error_msg       VARCHAR(2000) NULL,
  ip              VARCHAR(64)   NULL,
  cost_ms         BIGINT        NOT NULL DEFAULT 0,
  oper_time       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_oper_log_time ON sys_oper_log (oper_time);
COMMENT ON TABLE sys_oper_log IS '操作日志表';
COMMENT ON COLUMN sys_oper_log.oper_user_id IS '操作人id(NULL=匿名)';
COMMENT ON COLUMN sys_oper_log.oper_name IS '操作人用户名';
COMMENT ON COLUMN sys_oper_log.module IS '所属模块,如用户管理';
COMMENT ON COLUMN sys_oper_log.method IS '调用方法 类#方法';
COMMENT ON COLUMN sys_oper_log.params IS '入参摘要(脱敏+截断)';
COMMENT ON COLUMN sys_oper_log.status IS '0成功 1失败';
COMMENT ON COLUMN sys_oper_log.cost_ms IS '耗时毫秒';

CREATE TABLE IF NOT EXISTS sys_login_log (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username   VARCHAR(64)  NOT NULL,
  status     SMALLINT     NOT NULL DEFAULT 0,
  message    VARCHAR(255) NULL,
  ip         VARCHAR(64)  NULL,
  user_agent VARCHAR(512) NULL,
  login_time TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_login_log_time ON sys_login_log (login_time);
COMMENT ON TABLE sys_login_log IS '登录日志表';
COMMENT ON COLUMN sys_login_log.username IS '尝试登录的用户名';
COMMENT ON COLUMN sys_login_log.status IS '0成功 1失败';

CREATE TABLE IF NOT EXISTS sys_dict_type (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dict_name   VARCHAR(64)  NOT NULL,
  dict_type   VARCHAR(64)  NOT NULL,
  status      SMALLINT     NOT NULL DEFAULT 0,
  remark      VARCHAR(255) NULL,
  create_time TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_dict_type UNIQUE (dict_type)
);
COMMENT ON TABLE sys_dict_type IS '字典类型表';
COMMENT ON COLUMN sys_dict_type.dict_name IS '字典名称,如库存类型';
COMMENT ON COLUMN sys_dict_type.dict_type IS '字典类型键,全局唯一,如 wsm_stock_type';
COMMENT ON COLUMN sys_dict_type.status IS '0正常 1停用';

CREATE TABLE IF NOT EXISTS sys_dict_data (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dict_type   VARCHAR(64)  NOT NULL,
  dict_label  VARCHAR(64)  NOT NULL,
  dict_value  VARCHAR(64)  NOT NULL,
  sort_num    INT          NOT NULL DEFAULT 0,
  status      SMALLINT     NOT NULL DEFAULT 0,
  remark      VARCHAR(255) NULL,
  create_time TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_dict_value UNIQUE (dict_type, dict_value)
);
CREATE INDEX IF NOT EXISTS idx_dict_data_type ON sys_dict_data (dict_type);
COMMENT ON TABLE sys_dict_data IS '字典数据表';
COMMENT ON COLUMN sys_dict_data.dict_type IS '所属字典类型键(逻辑外键)';
COMMENT ON COLUMN sys_dict_data.dict_label IS '显示名';
COMMENT ON COLUMN sys_dict_data.status IS '0正常 1停用';

CREATE TABLE IF NOT EXISTS sys_file (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  original_name VARCHAR(255) NOT NULL,
  storage_key  VARCHAR(255) NOT NULL,
  size         BIGINT       NOT NULL,
  content_type VARCHAR(128) NOT NULL,
  biz_type     VARCHAR(32)  NOT NULL DEFAULT 'general',
  uploader_id  BIGINT       NOT NULL,
  create_time  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_file_key UNIQUE (storage_key)
);
CREATE INDEX IF NOT EXISTS idx_file_uploader ON sys_file (uploader_id);
COMMENT ON TABLE sys_file IS '文件记录表';
COMMENT ON COLUMN sys_file.original_name IS '原始文件名';
COMMENT ON COLUMN sys_file.storage_key IS '存储键(存储实现内部标识,如日期分桶+UUID)';
COMMENT ON COLUMN sys_file.size IS '文件大小(字节)';
COMMENT ON COLUMN sys_file.content_type IS '内容类型(上传时由原始名推导)';
COMMENT ON COLUMN sys_file.biz_type IS '业务类型:avatar头像 general通用';
COMMENT ON COLUMN sys_file.uploader_id IS '上传人id(sys_user.id)';

-- 头像列（幂等添加，历史库升级用）
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS avatar VARCHAR(64) NULL;
COMMENT ON COLUMN sys_user.avatar IS '头像文件id(sys_file.id),NULL=未设置';

-- 个人简介列（幂等添加，历史库升级用）
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS introduction VARCHAR(255) NULL;
COMMENT ON COLUMN sys_user.introduction IS '个人简介,NULL=未填写';

-- 邮箱列（幂等添加，历史库升级用）
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS email VARCHAR(255) NULL;
COMMENT ON COLUMN sys_user.email IS '邮箱,NULL=未填写';
