-- ============================================================
-- 存量库升级：LLM 模型配置（2026-09-21）
-- 内容：sys_llm_config 建表 + 「系统管理-模型配置」菜单与按钮权限 + 角色授权
-- 幂等：可重复执行（全部 NOT EXISTS 保护）；新库由 schema-postgres.sql + DatabaseSeeder 覆盖，无需本脚本
-- ============================================================

-- 1. 建表
CREATE TABLE IF NOT EXISTS sys_llm_config (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            VARCHAR(64)   NOT NULL,
  base_url        VARCHAR(255)  NOT NULL,
  api_key         VARCHAR(255)  NOT NULL DEFAULT '',
  model           VARCHAR(64)   NOT NULL,
  temperature     NUMERIC(3,1)  NULL,
  max_tokens      INT           NULL,
  timeout_seconds INT           NOT NULL DEFAULT 60,
  enabled         SMALLINT      NOT NULL DEFAULT 1,
  is_active       SMALLINT      NOT NULL DEFAULT 0,
  remark          VARCHAR(255)  NULL,
  create_time     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_llm_name UNIQUE (name)
);
COMMENT ON TABLE sys_llm_config IS 'LLM模型配置表(OpenAI兼容协议,全局唯一激活)';

-- 2. C 菜单：系统管理下的「模型配置」（parent = System 目录）
INSERT INTO sys_menu (parent_id, menu_name, menu_type, title, icon, order_num,
                      path, component, perm, visible, keep_alive, affix_tab, authority, status)
SELECT 4, 'SystemLlm', 'C', 'page.system.llm', 'ant-design:robot-outlined', 8,
       '/system/llm', '/system/llm/index', '', 0, 0, 0, 'super,admin', 0
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE menu_name = 'SystemLlm');

-- 3. F 按钮权限（挂在模型配置菜单下）
INSERT INTO sys_menu (parent_id, menu_name, menu_type, title, perm, visible, status)
SELECT m.id, 'Perm_System_Llm_' || split_part(p.perm, ':', 3), 'F', p.perm, p.perm, 0, 0
FROM sys_menu m
CROSS JOIN (VALUES ('System:Llm:List'), ('System:Llm:Add'), ('System:Llm:Edit'),
                   ('System:Llm:Delete'), ('System:Llm:Activate')) AS p(perm)
WHERE m.menu_name = 'SystemLlm'
  AND NOT EXISTS (SELECT 1 FROM sys_menu f WHERE f.perm = p.perm);

-- 4. 授权给 super(1) / admin(2)
INSERT INTO sys_role_menu (role_id, menu_id)
SELECT r.id, m.id
FROM sys_role r
CROSS JOIN sys_menu m
WHERE r.role_key IN ('super', 'admin')
  AND (m.menu_name = 'SystemLlm'
       OR (m.menu_type = 'F' AND m.perm LIKE 'System:Llm:%'))
  AND NOT EXISTS (SELECT 1 FROM sys_role_menu rm
                  WHERE rm.role_id = r.id AND rm.menu_id = m.id);
