-- 个人列表配置；可在存量 PostgreSQL 库重复执行。
CREATE TABLE IF NOT EXISTS sys_user_config (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      BIGINT       NOT NULL,
  config_key   VARCHAR(128) NOT NULL,
  config_value TEXT         NOT NULL,
  create_time  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_user_config_key UNIQUE (user_id, config_key)
);
COMMENT ON TABLE sys_user_config IS '用户个人配置(JSON数组)';
